#title: AVERtek # your name photo (or website title) here
logo1: "AVERtek-Logo-final-blue.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br> 
  <h3><b>ALEXAN BAHAY MEANS HOME</h3></b>
  <br><br>
  <b>ENVISION: 3D APARTMENT MODEL </b>  Tour 3D Model Below
  <br><br> 
  <b>EXPERIENCE: 4D AUGMENTED REALITY</b>  AR Walking Tour on Mobile Device
  <br><br>
  <b>VIEW:</b><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"</b><b> Luxury Living</b></a> 
  <br><br>
  <b>EXPLORE:</b><a href="https://alexanbahay.com/contact/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/contact/?utm_source=AVERtek&utm_medium=AR'); return false;"</b> <b> VIP Tour & Free Gift</a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-2 
